import type { Metadata } from 'next';
import Navbar from './common/components/navbar/navbar';
import { Kaisei_Decol } from 'next/font/google';
import './globals.css';

const kaiseiDecol = Kaisei_Decol({
  variable: '--font-kaisei-decol',
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'Poiema Ministries',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='overflow-x-hidden'>
      <body className={`${kaiseiDecol.variable} antialiased overflow-x-hidden`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
